#!/bin/bash

dir=oo1@stampede.tacc.utexas.edu:/scratch/02464/oo1/hmcrmsd/ala12_99sb

rsync -avz --exclude="bak*" --exclude="*.py" --exclude="*.sh" \
  --exclude=".*.swp" --exclude="#*" --exclude="*simul.o*" \
  --exclude="mdout.mdp" \
  $dir/*run[0-9] .

rsync -avz $dir/A12*.o* out/
